pysqlshop:
  outputs:
    dev:
      dataset: dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/app/dbt/keys/gcp-key.json
      location: europe-west4
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 6
      type: bigquery
  target: dev